### ISSUE TITLE
[Bug] sniper crashes randomly

### ISSUE THREAD

**Issue by nicrasga** [slow/nitro-sniper#117]
**Describe the bug**
The sniper works normally but after a while it crashes

**To Reproduce**
1. Go to 'cmd'
2. Start the sniper
2. Wait and it will randomly crash

**Expected behavior**
It shouldn't crash

**Screenshots**
https://i.imgur.com/54ZCZiG.png

**Additional context**
I'm using Node.js v14.17.0 and I'm on a rdp

**Comment by n1cky69** [comment]
@slow

**Comment by InimicalPart** [comment]
I am unable to reproduce this issue on version v14.17.0. Is it still crashing?

**Comment by slow** [comment]
This may happen if you run out of memory. If you have many alts on the same instance it may take up too much ram causing the sniper to crash. This is normal and doesn't have anything to do with the sniper. 

Any other issues might be because of the wrong node version.
The sniper has been tested on the following version and works perfectly fine: https://github.com/slow/nitro-sniper/issues/85#issuecomment-855992560
