### ISSUE TITLE
Heroku won't load and admin cmd won't detect

### ISSUE THREAD

**Issue by ohDevin** [slow/nitro-sniper#3]
**Describe the bug**
When I finish loading in the Heroku and changing the dyno thing, it won't load, it just kinda stays there, and when i go to the "open app," it says application error. 

Also for the admin cmd (local), i got it to work, but i tested it and it wont detect any nitro codes in discord

**To Reproduce**
i followed the steps, even downloaded visual studio for the admin cmd one

**Expected behavior**
For it to work :/

**Screenshots**
https://gyazo.com/b697fe22604bd8ac1fb31549bf01f379

**Comment by slow** [comment]
Yeah, that's normal as the heroku application is on a worker, meaning it doesnt have HTTP ports open. This means you cant access it from a website or the *.herokuapp.com url that you are provided with when you click `Open App`, the sniper doesn't have a dashboard so there's no reason for it to be hosted on a web worker which shuts down every 5 minutes unless it is visited by someone. Nothing is wrong with your sniper, you just need to visit `View Logs` instead of `Open App`.

**Comment by slow** [comment]
Can you let me know if you still face the issue where codes aren't detected after following the steps above?

**Comment by ohDevin** [comment]
I don't know what the hell I did, but in the beginning I followed those steps and nothing showed up. But now, the thing works! Thanks a lot!

**Comment by slow** [comment]
No worries, enjoy your free nitro :)

**Comment by ohDevin** [comment]
yoooo 18 seconds response? holy sh

**Comment by slow** [comment]
I have my alts in a bunch of servers from disboard, i usually leave every server and start by going on https://disboard.org/servers?sort=-member_count and log in on the alt on my desktop app so the invite can be prompted quicker, go down the list and join servers till you're about at 85-100 (100 is the max) and make sure you dont join the same servers on different alts.
