### ISSUE TITLE
[Bug] Verifying alternate accounts on invite snipe

### ISSUE THREAD

**Issue by LandenStephenss** [slow/nitro-sniper#84]
**Describe the bug**
  After sniping an invite the account will need to be verified, not sure if this is something to do with how the request is being sent or if discord is just retarded
**To Reproduce**
1. Let the bot snipe an invite

**Expected behavior**
  that doesnt happen

**Comment by dariot99** [comment]
Try enhancing the delay for sniping invites or simply disable it at all and join server manually (most of the invites that are sent are usually garbage anyways and typical Join4Join servers with 0 activity and 0 chances of nitro drops). 

I only got one alt that needed to be verified after that I joined (manually) too many servers in a short time span (probably also because the account had just been created) and I verified it using an online SMS service provider, paid 7 cents for a private number that worked fine for the verification.
